"""PDF Report Generator for AegisFIR.

Generates an A4 academic complaint intelligence dossier using ReportLab.
Includes academic disclaimers, complaint details, AI analysis findings,
crime classification, forensic evidence hashes, similar precedents, and legal references.
"""

from io import BytesIO
from typing import Any, Dict
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def create_report(complaint: Dict[str, Any], citizen_name: str = "Citizen") -> BytesIO:
    """Generate a clean, structured PDF complaint report."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#1e293b"),
        alignment=1
    )
    
    subtitle_style = ParagraphStyle(
        "DocSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=14,
        textColor=colors.HexColor("#475569"),
        alignment=1
    )

    disclaimer_style = ParagraphStyle(
        "Disclaimer",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#991b1b"),
        alignment=1
    )
    
    section_heading = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=15,
        textColor=colors.HexColor("#0f172a"),
        spaceBefore=8,
        spaceAfter=4
    )

    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#334155")
    )
    
    bold_body = ParagraphStyle(
        "BoldBody",
        parent=body_style,
        fontName="Helvetica-Bold"
    )

    story = []

    # 1. Header Banner
    story.append(Paragraph("AEGISFIR", title_style))
    story.append(Paragraph("AI-Assisted Smart Complaint Intelligence & Case Report", subtitle_style))
    story.append(Spacer(1, 4))
    
    # Disclaimer Box
    disclaimer_table = Table(
        [[Paragraph("<b>ACADEMIC DEMONSTRATION NOTICE:</b> This document is generated by an academic demonstration system. It is <u>NOT an official First Information Report (FIR)</u> or legal statutory document. All AI predictions, legal citations, and similarity scores are for educational evaluation only.", disclaimer_style)]],
        colWidths=[520]
    )
    disclaimer_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#fef2f2")),
        ("BORDER", (0, 0), (-1, -1), 1, colors.HexColor("#f87171")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(disclaimer_table)
    story.append(Spacer(1, 10))

    # 2. Complaint Basic Metadata Table
    status_text = str(complaint.get("status", "SUBMITTED")).replace("_", " ")
    meta_data = [
        [
            Paragraph("<b>Complaint ID:</b>", bold_body), Paragraph(str(complaint.get("id", "N/A")), body_style),
            Paragraph("<b>Current Status:</b>", bold_body), Paragraph(f"<b>{status_text}</b>", bold_body)
        ],
        [
            Paragraph("<b>Complainant:</b>", bold_body), Paragraph(str(citizen_name), body_style),
            Paragraph("<b>Incident Date:</b>", bold_body), Paragraph(str(complaint.get("incident_date", "N/A")), body_style)
        ],
        [
            Paragraph("<b>Location:</b>", bold_body), Paragraph(str(complaint.get("location", "N/A")), body_style),
            Paragraph("<b>Incident Category:</b>", bold_body), Paragraph(str(complaint.get("incident_type", "General")), body_style)
        ],
        [
            Paragraph("<b>Reported On:</b>", bold_body), Paragraph(str(complaint.get("created_at", "N/A")), body_style),
            Paragraph("<b>Contact Details:</b>", bold_body), Paragraph(str(complaint.get("contact_info", "N/A")), body_style)
        ]
    ]
    meta_table = Table(meta_data, colWidths=[100, 160, 100, 160])
    meta_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
        ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 10))

    # 3. Incident Statement
    story.append(Paragraph("INCIDENT STATEMENT", section_heading))
    story.append(Paragraph(f"<b>Subject:</b> {complaint.get('title', 'Untitled')}", bold_body))
    story.append(Spacer(1, 3))
    story.append(Paragraph(str(complaint.get("description", "No description provided.")), body_style))
    story.append(Spacer(1, 8))

    # 4. ML Crime Classification Box
    prediction = complaint.get("crime_prediction") or {}
    pred_cat = prediction.get("category", complaint.get("incident_type", "Pending Analysis"))
    pred_conf = prediction.get("confidence", "N/A")
    pred_model = prediction.get("model", "TF-IDF + Logistic Regression")
    
    ml_rows = [
        [
            Paragraph("<b>Predicted Crime Classification:</b>", bold_body),
            Paragraph(f"<font color='#0284c7'><b>{pred_cat}</b></font> ({pred_conf}% confidence)", bold_body),
            Paragraph("<b>Model Architecture:</b>", bold_body),
            Paragraph(str(pred_model), body_style)
        ]
    ]
    ml_table = Table(ml_rows, colWidths=[150, 150, 110, 110])
    ml_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f0f9ff")),
        ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#7dd3fc")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(Paragraph("MACHINE LEARNING CLASSIFICATION", section_heading))
    story.append(ml_table)
    story.append(Spacer(1, 8))

    # 5. AI Complaint Analysis
    analysis = complaint.get("ai_analysis") or {}
    if analysis and analysis.get("summary"):
        story.append(Paragraph("AI COMPLAINT ANALYSIS FINDINGS", section_heading))
        summary_p = Paragraph(f"<b>Executive Summary:</b> {analysis.get('summary', '')}", body_style)
        story.append(summary_p)
        story.append(Spacer(1, 4))
        
        # Missing & Risk
        missing_items = ", ".join(analysis.get("missing_information", [])) or "None identified"
        risks_items = ", ".join(analysis.get("risk_flags", [])) or "Standard Priority"
        
        ai_table_data = [
            [Paragraph("<b>Risk Flags:</b>", bold_body), Paragraph(f"<font color='#b91c1c'>{risks_items}</font>", body_style)],
            [Paragraph("<b>Missing Investigation Facts:</b>", bold_body), Paragraph(missing_items, body_style)],
            [Paragraph("<b>Evidence Mentioned in Text:</b>", bold_body), Paragraph(", ".join(analysis.get("evidence_mentioned", [])) or "None", body_style)],
            [Paragraph("<b>Analysis Mode:</b>", bold_body), Paragraph(f"{analysis.get('mode', 'Demo AI Engine')}", body_style)]
        ]
        ai_table = Table(ai_table_data, colWidths=[140, 380])
        ai_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#fafaf9")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#d6d3d1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e7e5e4")),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(ai_table)
        story.append(Spacer(1, 8))

    # 6. Forensic Evidence
    evidence_list = complaint.get("evidence", [])
    if evidence_list:
        story.append(Paragraph(f"FORENSIC EVIDENCE VAULT ({len(evidence_list)} Files Attached)", section_heading))
        ev_header = [Paragraph("<b>File Name</b>", bold_body), Paragraph("<b>Type / Size</b>", bold_body), Paragraph("<b>Cryptographic SHA-256 Hash</b>", bold_body)]
        ev_rows = [ev_header]
        for ev in evidence_list:
            size_kb = f"{round(ev.get('file_size', 0) / 1024, 1)} KB"
            hash_snippet = ev.get("sha256", "N/A")
            ev_rows.append([
                Paragraph(str(ev.get("filename", "evidence")), body_style),
                Paragraph(f"{ev.get('file_type', 'bin').upper()} | {size_kb}", body_style),
                Paragraph(f"<font size='7'>{hash_snippet}</font>", body_style)
            ])
        ev_table = Table(ev_rows, colWidths=[130, 90, 300])
        ev_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(ev_table)
        story.append(Spacer(1, 8))

    # 7. Similar Historical Cases & Legal RAG
    sim_cases = complaint.get("similar_cases", [])
    legal_refs = complaint.get("legal_references", [])
    
    if sim_cases:
        story.append(Paragraph("HISTORICAL SIMILAR CASE PRECEDENTS (FAISS Vector Search)", section_heading))
        sim_data = [[Paragraph("<b>Case ID</b>", bold_body), Paragraph("<b>Title</b>", bold_body), Paragraph("<b>Semantic Similarity</b>", bold_body)]]
        for sc in sim_cases[:3]:
            sim_data.append([
                Paragraph(str(sc.get("id")), body_style),
                Paragraph(str(sc.get("title")), body_style),
                Paragraph(f"<b>{sc.get('similarity', 0)}%</b> match", body_style)
            ])
        sim_table = Table(sim_data, colWidths=[80, 330, 110])
        sim_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f8fafc")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(sim_table)
        story.append(Spacer(1, 6))

    if legal_refs:
        story.append(Paragraph("STATUTORY LEGAL REFERENCES (RAG Retrieval)", section_heading))
        leg_data = [[Paragraph("<b>Ref ID</b>", bold_body), Paragraph("<b>Statute / Section Title</b>", bold_body), Paragraph("<b>Match Relevance</b>", bold_body)]]
        for lr in legal_refs[:3]:
            leg_data.append([
                Paragraph(str(lr.get("id")), body_style),
                Paragraph(str(lr.get("title")), body_style),
                Paragraph(f"{lr.get('similarity', 0)}% relevance", body_style)
            ])
        leg_table = Table(leg_data, colWidths=[80, 330, 110])
        leg_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f8fafc")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(leg_table)
        story.append(Spacer(1, 8))

    # 8. Investigation Notes (if any)
    notes = complaint.get("investigation_notes", [])
    if notes:
        story.append(Paragraph("OFFICER INVESTIGATION NOTES", section_heading))
        for note in notes[-3:]:
            story.append(Paragraph(f"• <b>[{note.get('updated_at', '')}] {note.get('updated_by', 'Officer')}:</b> {note.get('note', '')}", body_style))
        story.append(Spacer(1, 6))

    # Footer Divider & Sign-off
    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cbd5e1"), spaceAfter=6))
    story.append(Paragraph("AegisFIR — Final Year CSE(AIML) Academic Project Prototype • Powered by FastAPI, Scikit-Learn & React", disclaimer_style))
    
    doc.build(story)
    buffer.seek(0)
    return buffer